Repository farisfaikar/ComicU, pull requests merged in 2023-12, with the labels that each got.

#34 [fix] Frontend #3
  resources/views/category/index-category.blade.php
  resources/views/comic/index-comic.blade.php
  resources/views/home.blade.php
  resources/views/layouts/guest.blade.php
  resources/views/review/index-review.blade.php
  resources/views/transaction/index-transaction.blade.php
Labels: frontend

#35 [feat] Add Google Login SSO
  app/Http/Controllers/GoogleController.php
  app/Models/User.php
  composer.json
  composer.lock
  config/services.php
  database/migrations/2023_05_25_104012_add_column_google_id_to_users_table.php
  resources/views/auth/login.blade.php
  routes/web.php
Labels: backend

#36 feat-add-component_searching
  app/Http/Controllers/ReviewController.php
  app/Http/Controllers/TransactionController.php
  resources/views/category/index-category.blade.php
  resources/views/comic/index-comic.blade.php
  resources/views/components/searchbar.blade.php
  resources/views/review/edit-review.blade.php
  resources/views/review/index-review.blade.php
  resources/views/transaction/edit-transaction.blade.php
  resources/views/transaction/index-transaction.blade.php
  routes/web.php
Labels: bug, documentation, backend, frontend

#37 feat-add-styling_pagination
  app/Providers/AppServiceProvider.php
  resources/views/components/pagination.blade.php
Labels: documentation, frontend

#39 Aditya feat upload image
  app/Http/Controllers/ComicController.php
  app/Models/Comic.php
  config/filesystems.php
  database/migrations/2023_11_14_00000_create_comics_table.php
  resources/views/comic/create-comic.blade.php
  resources/views/comic/index-comic.blade.php
Labels: documentation, backend

#41 feat: add user crud
  app/Http/Controllers/UserController.php
  resources/views/layouts/navigation.blade.php
  resources/views/users/create-user.blade.php
  resources/views/users/edit.blade.php
  resources/views/users/index-user.blade.php
  routes/web.php
Labels: backend

#46 feat: add price comic
  app/Http/Controllers/ComicController.php
  app/Models/Comic.php
  database/factories/ComicFactory.php
  database/migrations/2023_11_14_00000_create_comics_table.php
  database/seeders/ComicSeeder.php
  resources/views/comic/create-comic.blade.php
  resources/views/comic/edit-comic.blade.php
  resources/views/comic/index-comic.blade.php
  resources/views/home.blade.php
Labels: backend, frontend

#48 [build] npm run build
  .gitignore
  public/build/assets/app-7b7d18fe.css
  public/build/assets/app-89c2e21b.js
  public/build/manifest.json
Labels: build

#49 [database] Fix Comic Factory and Seeder
  database/factories/ComicFactory.php
  database/seeders/ComicSeeder.php
Labels: bug, backend

#53 feat-export-excel
  app/Exports/ExportComic.php
  app/Http/Controllers/ComicController.php
  composer.json
  composer.lock
  config/app.php
  config/excel.php
  resources/views/comic/index-comic.blade.php
  resources/views/comic/table-comic.blade.php
  routes/web.php
Labels: documentation, backend

#52 [fix] General Fixes
  resources/views/auth/login.blade.php
  resources/views/components/pagination.blade.php
  resources/views/dashboard.blade.php
  resources/views/home.blade.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/guest.blade.php
  resources/views/layouts/navigation-guest.blade.php
  resources/views/layouts/navigation.blade.php
  routes/auth.php
Labels: bug, backend, frontend

#55 feat-midtrans
  app/Http/Controllers/TesController.php
  app/Models/Order.php
  composer.json
  composer.lock
  config/midtrans.php
  database/migrations/2023_12_06_154425_create_orders_table.php
  resources/views/test/checkout.blade.php
  resources/views/test/index.blade.php
  routes/web.php
Labels: documentation, backend

#57 [devops] Create laravel.yml
  .github/workflows/laravel.yml
Labels: devops

#59 [frontend.ci] Upload Photo Preview
  .github/workflows/laravel.yml
  composer.lock
  resources/views/comic/create-comic.blade.php
  resources/views/profile/partials/update-profile-information-form.blade.php
  routes/auth.php
  tests/Feature/Auth/PasswordUpdateTest.php
Labels: frontend, devops

#60 add about us
  app/Http/Controllers/AboutController.php
  composer.lock
  public/img/foto-aditya.jpg
  public/img/foto-faris.jpg
  public/img/hasby.jpg
  public/img/iskandar.jpg
  public/img/jull.jpg
  resources/views/about.blade.php
  resources/views/layouts/guest.blade.php
  routes/web.php
Labels: backend

#65 fix:home cards responsive
  resources/views/home.blade.php
Labels: frontend

#66 [ci] Add npm run build into laravel.yml and other frontend fixes
  .github/workflows/laravel.yml
  resources/views/about.blade.php
  resources/views/components/pagination.blade.php
  resources/views/home.blade.php
  resources/views/layouts/guest.blade.php
  routes/web.php
Labels: frontend, build, devops

#68 create_detail_comic
  app/Http/Controllers/HomeController.php
  resources/views/home.blade.php
  resources/views/home/detail-comic.blade.php
  resources/views/layouts/guest.blade.php
  routes/web.php
Labels: backend

#80 [fix] General Fixes
  app/Http/Controllers/OrderController.php
  database/seeders/CategorySeeder.php
  resources/views/comic/index-comic.blade.php
  resources/views/home/detail-comic.blade.php
  resources/views/layouts/guest.blade.php
  resources/views/review/index-review.blade.php
  resources/views/test/order.blade.php
  resources/views/transaction/index-transaction.blade.php
  routes/web.php
Labels: bug, backend, frontend

#81 Add Contact Us
  app/Http/Controllers/ContactController.php
  app/Models/ContactUs.php
  database/migrations/2023_12_08_075743_create_contact_us_table.php
  resources/views/contact/contact.blade.php
  resources/views/contact/index-contact.blade.php
  resources/views/layouts/guest.blade.php
  resources/views/layouts/navigation.blade.php
  routes/web.php
Labels: backend

#83 fix:tabel views
  public/build/assets/app-01076dd0.css
  public/build/assets/app-5e294837.css
  public/build/manifest.json
  resources/views/category/create-category.blade.php
  resources/views/category/edit-category.blade.php
  resources/views/comic/create-comic.blade.php
  resources/views/comic/edit-comic.blade.php
  resources/views/comic/index-comic.blade.php
  resources/views/review/create-review.blade.php
  resources/views/review/edit-review.blade.php
  resources/views/transaction/create-transaction.blade.php
  resources/views/transaction/edit-transaction.blade.php
Labels: frontend

#86 [feat] add midtrans script
  resources/views/test/order.blade.php
Labels: backend
