Repository farisfaikar/ComicU, pull requests merged in 2023-11, with the labels that each got.

#3 feat add aditya eka to team member in readme
  README.md
Labels: documentation

#5 feat: readme team members
  README.md
Labels: documentation

#6 Hasby.update homepage
  resources/views/home.blade.php
  tailwind.config.js
Labels: frontend

#8 [minor] Refactor Transaction and Comic Index
  resources/views/comic/index-comic.blade.php
  resources/views/transaction/index-transaction.blade.php
Labels: frontend

#9 [hotfix] Remove Duplicate Comic Migration
  database/migrations/2023_11_16_124202_create_comics_table.php
Labels: bug

#13 Major Rewrite On All Departments
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/TransactionController.php
  app/Models/Transaction.php
  database/factories/ComicFactory.php
  database/factories/TransactionFactory.php
  database/seeders/ComicSeeder.php
  database/seeders/TransactionSeeder.php
  public/img/comicu-logo.png
  resources/views/auth/confirm-password.blade.php
  resources/views/auth/forgot-password.blade.php
  resources/views/auth/login.blade.php
  resources/views/auth/register.blade.php
  resources/views/auth/verify-email.blade.php
  resources/views/comic/create-comic.blade.php
  resources/views/comic/edit-comic.blade.php
  resources/views/comic/index-comic.blade.php
  resources/views/components/application-logo.blade.php
  resources/views/components/danger-button.blade.php
  resources/views/components/dropdown-link.blade.php
  resources/views/components/dropdown.blade.php
  resources/views/components/input-label.blade.php
  resources/views/components/modal.blade.php
  resources/views/components/nav-link.blade.php
  resources/views/components/primary-button.blade.php
  resources/views/components/responsive-nav-link.blade.php
  resources/views/components/secondary-button.blade.php
  resources/views/components/text-input.blade.php
  resources/views/dashboard.blade.php
  resources/views/home.blade.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/guest.blade.php
  resources/views/layouts/navigation-guest.blade.php
  resources/views/layouts/navigation.blade.php
  resources/views/profile/edit.blade.php
  resources/views/profile/partials/delete-user-form.blade.php
  resources/views/profile/partials/update-password-form.blade.php
  resources/views/profile/partials/update-profile-information-form.blade.php
  resources/views/transaction/create-transaction.blade.php
  resources/views/transaction/index-transaction.blade.php
  routes/web.php
  tailwind.config.js
Labels: enhancement, backend, frontend

#12 create crud review
  app/Http/Controllers/ReviewController.php
  app/Models/Review.php
  database/migrations/2023_11_19_063121_create_reviews_table.php
  database/seeders/ReviewSeeder.php
  resources/views/layouts/navigation.blade.php
  resources/views/review/create-review.blade.php
  resources/views/review/edit-review.blade.php
  resources/views/review/index-review.blade.php
  routes/web.php
Labels: backend

#14 feat: add crud category
  app/Http/Controllers/CategoryController.php
  app/Http/Requests/StorecategoryRequest.php
  app/Http/Requests/UpdatecategoryRequest.php
  app/Models/Category.php
  app/Policies/CategoryPolicy.php
  database/factories/CategoryFactory.php
  database/migrations/2023_11_16_143842_create_categories_table.php
  database/seeders/CategorySeeder.php
  resources/views/categories.blade.php
  resources/views/category/create-category.blade.php
  resources/views/category/edit-category.blade.php
  resources/views/category/index-category.blade.php
  resources/views/layouts/navigation.blade.php
  routes/web.php
Labels: backend

#15 Minor Changes
  app/Http/Controllers/ReviewController.php
  app/Models/Review.php
  database/factories/ReviewFactory.php
  database/migrations/2023_11_19_063121_create_reviews_table.php
  database/seeders/DatabaseSeeder.php
  database/seeders/ReviewSeeder.php
  database/seeders/UserSeeder.php
  resources/views/comic/index-comic.blade.php
  resources/views/layouts/navigation.blade.php
  resources/views/review/index-review.blade.php
Labels: bug

#16 feat_fixing-layout-table_categories
  resources/views/category/create-category.blade.php
  resources/views/category/edit-category.blade.php
  resources/views/category/index-category.blade.php
Labels: frontend

#18 feat-searching-comics
  app/Http/Controllers/ComicController.php
  resources/views/comic/index-comic.blade.php
  resources/views/layouts/navigation.blade.php
  routes/web.php
Labels: documentation, backend, frontend

#21 [refactor] Connect Comic and Category
  app/Http/Controllers/ComicController.php
  app/Models/Comic.php
  database/factories/ComicFactory.php
  database/migrations/2023_11_14_00000_create_categories_table.php
  database/migrations/2023_11_14_00000_create_comics_table.php
  database/migrations/2023_11_21_040949_update_comics_table.php
  database/seeders/CategorySeeder.php
  database/seeders/ComicSeeder.php
  database/seeders/DatabaseSeeder.php
  resources/views/comic/create-comic.blade.php
  resources/views/comic/edit-comic.blade.php
  resources/views/comic/index-comic.blade.php
Labels: enhancement, backend, frontend

#22 feat: fix-reviews
  app/Http/Controllers/ReviewController.php
  resources/views/review/create-review.blade.php
  resources/views/review/edit-review.blade.php
Labels: bug

#24 update homepage
  resources/views/auth/login.blade.php
  resources/views/auth/register.blade.php
  resources/views/components/primary-button.blade.php
  resources/views/layouts/guest.blade.php
Labels: frontend

#26 fix: category views and contoller
  app/Http/Controllers/CategoryController.php
  resources/views/category/create-category.blade.php
  resources/views/category/edit-category.blade.php
  resources/views/category/index-category.blade.php
Labels: backend, frontend

#27 [WIP] Dashboard Chart and Cards
  app/Http/Controllers/DashboardController.php
  database/factories/ComicFactory.php
  database/factories/TransactionFactory.php
  package-lock.json
  package.json
  resources/views/dashboard.blade.php
  resources/views/home.blade.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/guest.blade.php
  routes/web.php
  tailwind.config.js
Labels: enhancement, backend, frontend

#28 [chore] Fix Codes
  app/Http/Controllers/CategoryController.php
  app/Http/Controllers/DashboardController.php
  resources/views/comic/index-comic.blade.php
  resources/views/dashboard.blade.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/guest.blade.php
  resources/views/review/index-review.blade.php
Labels: bug, enhancement, backend, frontend

#30 feat-styling_table_and_searching
  app/Providers/AppServiceProvider.php
  resources/views/category/index-category.blade.php
  resources/views/comic/index-comic.blade.php
  resources/views/review/index-review.blade.php
Labels: frontend

#31 feat: add transaction crud
  app/Http/Controllers/TransactionController.php
  app/Models/Transaction.php
  resources/views/transaction/create-transaction.blade.php
  resources/views/transaction/edit-transaction.blade.php
  resources/views/transaction/index-transaction.blade.php
Labels: backend

#32 feat:colors_category_validatecategorycontrollers
  app/Http/Controllers/CategoryController.php
  resources/views/category/index-category.blade.php
Labels: frontend
